
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-test
spec:
  description: Test the go application
  params:
    - name: go-image
      default: registry.access.redhat.com/ubi8/go-toolset:latest
      type: string
  steps:
    - name: go-build
      image: $(params.go-image)
      workingDir: $(workspaces.source.path)/code
      command:
        - go
      args:
        - test
        - -v
  workspaces:
    - description: Persistance Storage between Pods.
      name: source
