apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-go-app
spec:
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/greet"
        backend:
          service:
            name: go-web-app-svc
            port:
              number: 8080